server {
    listen 80;
    server_name web-app-backend.duckdns.org;

    # LB Health Check
    location /health {
        return 200 'healthy';
        add_header Content-Type text/plain;
    }

    location /api {
        proxy_pass http://backend-api:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }
}