name: Backend CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_IP }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            # Define exact paths
            NODE_PATH="/home/praveenbesetti09/.nvm/versions/node/v24.14.0/bin"
            PROJECT_DIR="/var/www/backend"

            # 1. Update Permissions and Git
            sudo chown -R praveenbesetti09:praveenbesetti09 $PROJECT_DIR
            git config --global --add safe.directory $PROJECT_DIR

            # 2. Pull latest code
            cd $PROJECT_DIR && git pull origin main

            # 3. Create .env file
            echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

            # 4. Install Dependencies (Forced via Absolute Path + Sudo)
            sudo $NODE_PATH/npm install --production

            # 5. PM2 Restart (Forced via Absolute Path + Sudo)
            sudo $NODE_PATH/pm2 delete backend-api || true
            sudo $NODE_PATH/pm2 start server.js --name "backend-api"
            sudo $NODE_BIN/pm2 save

            # 6. Restart Nginx
            sudo systemctl restart nginx